# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 18:26
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_number',
            field=models.CharField(max_length=48, null=True, unique=True),
        ),
    ]
