# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 20:12
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170130_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_gift_certificates', 'Can manage Gift Certificates'),)},
        ),
    ]
