# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 04:39
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_slug'),
        ('users', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=30, null=True)),
                ('address2', models.CharField(max_length=30, null=True)),
                ('cell_phone', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=3, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=3, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubCorp',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('employer', models.CharField(max_length=80, null=True)),
                ('position', models.CharField(max_length=30, null=True)),
                ('statement_cycle_id', models.CharField(max_length=2, null=True)),
                ('show_in_roster', models.BooleanField(default=False)),
                ('prepaid_cart', models.BooleanField(default=False)),
                ('email_dues_notice', models.BooleanField(default=False)),
                ('email_statement', models.BooleanField(default=False)),
                ('subscribe_score', models.BooleanField(default=False)),
                ('subscribe_clublink_info', models.BooleanField(default=False)),
                ('subscribe_club_info', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='users.Address')),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_profile', to='users.Address')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_corp', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='clubcorp_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='option_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_users', to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Resigned'), ('S', 'Suspended')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.UserCategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='clubcorp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.ClubCorp'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.UserType'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('type', 'user')]),
        ),
    ]
