# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 05:41
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateField(default=clublink.base.utils.today),
        ),
    ]
