# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 12:17
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170215_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_profile', to='users.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mailing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_profile', to='users.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.UserCategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clubcorp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.ClubCorp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_users', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.UserType'),
        ),
    ]
