# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170228_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
