# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userpermissions_can_impersonate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.BooleanField(default=False),
        ),
    ]
