# Generated by Django 2.0.2 on 2018-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20171227_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='_type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('B', 'Business'), ('C', 'Cottage'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
