# Generated by Django 2.0.2 on 2018-04-20 01:03

from django.db import migrations


def update_address_types(apps, schema_editor):

    pairs = {
        'BUSINESS': 'B',
        'COTTAGE': 'C',
        'HOME': 'H',
        'OTHER': 'O'
        }

    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Address = apps.get_model('users', 'Address')
    for k, v in pairs.items():
        subset = Address._default_manager.filter(
            type=k
            )
        # print(f'{k} count - {len(subset)}')
        subset.update(_type=v)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_address__type'),
    ]

    operations = [
        migrations.RunPython(update_address_types),
    ]
