# Generated by Django 2.0.2 on 2018-04-20 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180419_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_cell',
            field=models.ForeignKey(blank=True, help_text='ForeignKey to know which cell to show.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cell_profiles', to='users.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_phone',
            field=models.ForeignKey(blank=True, help_text='ForeignKey to know which phone to show.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_profiles', to='users.Address'),
        ),
    ]
