# Generated by Django 2.0.2 on 2018-04-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180419_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.ForeignKey(blank=True, help_text='ForeignKey to know which email to show.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_profiles', to='users.Address'),
        ),
    ]
