# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 13:42
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpnews',
            name='photo',
            field=models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('corp_news')),
        ),
    ]
