# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0042_auto_20170802_1721'),
        ('corp', '0002_auto_20170608_0942'),
    ]

    operations = [
        migrations.RenameModel('CorpNews', 'News'),
    ]
