# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def slugify_title(apps, schema_editor):
    News = apps.get_model('corp', 'News')

    for n in News.objects.all():
        n.slug = slugify(n.headline)
        n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0042_auto_20170802_1721'),
        ('corp', '0003_auto_20170814_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='clubs',
            field=models.ManyToManyField(related_name='news_items', to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_club_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_corp_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.RunPython(slugify_title, lambda x, y: None),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=128, unique=True)
        ),
    ]
