# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0004_auto_20170814_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='clubs',
            field=models.ManyToManyField(related_name='news', to='clubs.Club'),
        ),
    ]
