from django.conf.urls import url

from clublink.cms.modules.club_sites import views

from rest_framework.routers import DefaultRouter
from clublink.users.viewsets import MemberRosterViewSet

router = DefaultRouter()
router.register(r'members', MemberRosterViewSet)

urlpatterns = [
    
    # Club Site CMS
    url(r'^switch/$', views.SwitchClub.as_view(),
        name='club-site.switch-club'),
    url(r'^$', views.ClubSiteView.as_view(), name='club-site.home'),
    url(r'^(?P<club_pk>[0-9]+)/$',
        views.ClubSiteView.as_view(),
        name='club-site.home'),
    url(r'^(?P<club_pk>[0-9]+)/pages/$',
        views.PagesView.as_view(),
        name='club-site.pages'),
    url(r'^(?P<club_pk>[0-9]+)/pages/new/$',
        views.PagesAddView.as_view(),
        name='club-site.pages-add'),
    url(r'^(?P<club_pk>[0-9]+)/pages/reorder/$',
        views.PagesReorderView.as_view(),
        name='club-site.pages-reorder'),
    url(r'^(?P<club_pk>[0-9]+)/pages/(?P<page_pk>[0-9]+)/$',
        views.PagesEditView.as_view(),
        name='club-site.pages-edit'),
    url(r'^(?P<club_pk>[0-9]+)/pages/(?P<page_pk>[0-9]+)/delete/$',
        views.PagesDeleteView.as_view(),
        name='club-site.pages-delete'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/$',
        views.GalleryView.as_view(),
        name='club-site.gallery'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/new/$',
        views.GalleryAddView.as_view(),
        name='club-site.gallery-add'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/reorder/$',
        views.GalleryReorderView.as_view(),
        name='club-site.gallery-reorder'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/(?P<gallery_pk>[0-9]+)/$',
        views.GalleryEditView.as_view(),
        name='club-site.gallery-edit'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/(?P<gallery_pk>[0-9]+)/delete/$',
        views.GalleryDeleteView.as_view(),
        name='club-site.gallery-delete'),
    url(r'^(?P<club_pk>[0-9]+)/gallery/(?P<gallery_pk>[0-9]+)/image/(?P<image_pk>[0-9]+)/delete/$',
        views.GalleryImageDeleteView.as_view(),
        name='club-site.gallery-image-delete'),
    url(r'^(?P<club_pk>[0-9]+)/team-members/$',
        views.TeamMemberView.as_view(),
        name='club-site.team-members'),
    url(r'^(?P<club_pk>[0-9]+)/team-members/new/$',
        views.TeamMemberAddView.as_view(),
        name='club-site.team-members-add'),
    url(r'^(?P<club_pk>[0-9]+)/team-members/reorder/$',
        views.TeamMemberReorderView.as_view(),
        name='club-site.team-members-reorder'),
    url(r'^(?P<club_pk>[0-9]+)/team-members/(?P<team_member_pk>[0-9]+)/$',
        views.TeamMemberEditView.as_view(),
        name='club-site.team-members-edit'),
    url(r'^(?P<club_pk>[0-9]+)/team-members/(?P<team_member_pk>[0-9]+)/delete/$',
        views.TeamMemberDeleteView.as_view(),
        name='club-site.team-members-delete'),
    url(r'^(?P<club_pk>[0-9]+)/news/$',
        views.NewsView.as_view(),
        name='club-site.news'),
    url(r'^(?P<club_pk>[0-9]+)/news/new/$',
        views.NewsAddView.as_view(),
        name='club-site.news-add'),
    url(r'^(?P<club_pk>[0-9]+)/news/(?P<news_item_pk>[0-9]+)/$',
        views.NewsEditView.as_view(),
        name='club-site.news-edit'),
    url(r'^(?P<club_pk>[0-9]+)/news/(?P<news_item_pk>[0-9]+)/delete/$',
        views.NewsDeleteView.as_view(),
        name='club-site.news-delete'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/$',
        views.CalendarView.as_view(),
        name='club-site.calendar'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/new/$',
        views.CalendarAddView.as_view(),
        name='club-site.calendar-add'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/register/$',
        views.CalendarRegisterView.as_view(),
        name='club-site.calendar-register'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/event-rsvp-delete/(?P<rsvp_pk>[0-9]+)/$',
        views.CalendarEventRSVPDeleteView.as_view(),
        name='club-site.calendar-event-rsvp-delete'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/$',
        views.CalendarEditView.as_view(),
        name='club-site.calendar-edit'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/delete/$',
        views.CalendarBulkDeleteView.as_view(),
        name='club-site.calendar-delete'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/export/$',
        views.CalendarExportView.as_view(),
        name='club-site.calendar-export'),
    url(r'^(?P<club_pk>[0-9]+)/calendar/(?P<event_pk>[0-9]+)/message/$',
        views.CalendarMessageView.as_view(),
        name='club-site.calendar-message'),
]
