# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 04:51
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170216_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='club',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
