# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 07:35
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170217_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('sort', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='cms.Page')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('gallery'))),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.Gallery')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([('page', 'slug')]),
        ),
    ]
