# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 12:41
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20170216_2302'),
        ('cms', '0007_auto_20170217_0735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('club', 'slug', 'parent')]),
        ),
    ]
