# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20170217_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_system_page',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
