# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 11:30
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_club_bilingual'),
        ('cms', '0012_auto_20170221_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('sort', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='clubs.Club')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='ClubGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('gallery/club/'))),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.ClubGallery')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='page',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AlterUniqueTogether(
            name='clubgallery',
            unique_together=set([('club', 'slug')]),
        ),
    ]
