# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20170405_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubgallery',
            options={'ordering': ('sort', '-id')},
        ),
        migrations.AlterModelOptions(
            name='clubgalleryimage',
            options={'ordering': ('sort', '-id')},
        ),
    ]
