# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 20:45
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170405_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('slug', models.CharField(max_length=64)),
                ('image', models.ImageField(null=True, upload_to=clublink.base.utils.RandomizedUploadPath('page'))),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CorpPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.CorpPage')),
            ],
        ),
        migrations.CreateModel(
            name='CorpSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2)),
                ('slug', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='cms.CorpPage')),
            ],
        ),
        migrations.RenameModel(
            old_name='Page',
            new_name='ClubPage',
        ),
        migrations.RenameModel(
            old_name='Snippet',
            new_name='ClubSnippet',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ClubImage',
        ),
        migrations.AddField(
            model_name='clubimage',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='corpimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.CorpPage'),
        ),
        migrations.AlterUniqueTogether(
            name='corpsnippet',
            unique_together=set([('page', 'locale', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='corppage',
            unique_together=set([('slug', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='corpimage',
            unique_together=set([('page', 'locale', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='clubimage',
            unique_together=set([('page', 'locale', 'slug')]),
        ),
    ]
