# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 20:57
from __future__ import unicode_literals

from django.db import migrations


def migrate_page(apps, schema_editor, page=None, new_parent=None):
    ClubPage = apps.get_model('cms', 'ClubPage')
    CorpPage = apps.get_model('cms', 'CorpPage')
    CorpSnippet = apps.get_model('cms', 'CorpSnippet')
    CorpImage = apps.get_model('cms', 'CorpImage')

    pages = ClubPage.objects.filter(parent=None) if page is None else page.children.all()

    for club_page in pages:
        if club_page.club is None:
            corp_page = CorpPage.objects.create(
                slug=club_page.slug, parent=new_parent, is_locked=club_page.is_locked)

            for s in club_page.snippets.all():
                CorpSnippet.objects.create(
                    page=corp_page, locale=s.locale, slug=s.slug, content=s.content)

            for i in club_page.images.all():
                CorpImage.objects.create(
                    page=corp_page, locale=i.locale, slug=i.slug, image=i.image)

            migrate_page(apps, schema_editor, club_page, corp_page)

            club_page.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20170507_1645'),
    ]

    operations = [
        migrations.RunPython(migrate_page),
    ]
