# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 01:30
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


def reslug_home(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')
    CorpPage = apps.get_model('cms', 'CorpPage')

    for p in ClubPage.objects.filter(slug='home', parent=None):
        p.slug = ''
        p.save()

    for p in CorpPage.objects.filter(slug='home', parent=None):
        p.slug = ''
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20170507_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Everyone'), (1, 'Members Only'), (2, 'Non-Members Only')], default=0),
        ),
        migrations.RunPython(reslug_home, lambda x, y: None)
    ]
