# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 05:19
# flake8: noqa

from __future__ import unicode_literals

import clublink.base.utils
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20170625_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpWeddingGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('gallery/club/'))),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.CorpWeddingGallery')),
            ],
            options={
                'ordering': ('sort', '-id'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
