# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 12:40
from __future__ import unicode_literals

from django.db import migrations


def recase_names(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')
    CorpPage = apps.get_model('cms', 'CorpPage')

    for p in ClubPage.objects.all():
        p.name = p.name.replace('-', ' ').capitalize()
        p.save()

    for p in CorpPage.objects.filter(slug='home', parent=None):
        p.name = p.name.replace('-', ' ').capitalize()
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20170626_0835'),
    ]

    operations = [
        migrations.RunPython(recase_names),
    ]
