# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


def generate_full_path_recursive(page):
    page.full_path = page.parent.full_path if page.parent else ''
    if page.slug:
        page.full_path += '{}/'.format(page.slug)
    page.save()
    for child in page.children.all():
        generate_full_path_recursive(child)


def populate_full_path(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')
    CorpPage = apps.get_model('cms', 'CorpPage')

    for p in ClubPage.objects.filter(parent=None):
        generate_full_path_recursive(p)

    for p in CorpPage.objects.filter(parent=None):
        generate_full_path_recursive(p)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20170702_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='full_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='full_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(populate_full_path, lambda x, y: None),
        migrations.AlterField(
            model_name='clubpage',
            name='full_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='corppage',
            name='full_path',
            field=models.CharField(max_length=255),
        ),
    ]
