# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_auto_20170626_0945'),
        ('cms', '0024_auto_20170702_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpage',
            name='full_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corppage',
            name='full_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clubpage',
            unique_together=set([('club', 'full_path')]),
        ),
        migrations.AlterUniqueTogether(
            name='corppage',
            unique_together=set([('full_path',)]),
        ),
    ]
