# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20170702_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='show_address_bar',
            field=models.BooleanField(default=True),
        ),
    ]
