# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 20:47
from __future__ import unicode_literals

from django.db import migrations


def generate_full_path_recursive(page):
    page.full_path = '{}/'.format(page.parent.full_path) if page.parent else ''
    if page.slug:
        page.full_path += page.slug
    page.save()
    for child in page.children.all():
        generate_full_path_recursive(child)


def fix_full_path(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')
    CorpPage = apps.get_model('cms', 'CorpPage')

    for p in ClubPage.objects.filter(parent=None):
        generate_full_path_recursive(p)

    for p in CorpPage.objects.filter(parent=None):
        generate_full_path_recursive(p)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20170702_0949'),
    ]

    operations = [
        migrations.RunPython(fix_full_path),
    ]
