# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 20:52
from __future__ import unicode_literals

from django.db import migrations


def delete_signature_events_page(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')
    ClubPage.objects.filter(full_path='events/signature').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20170702_1647'),
    ]

    operations = [
        migrations.RunPython(delete_signature_events_page),
    ]
