# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 21:49
from __future__ import unicode_literals

from django.db import migrations


CREATE = {
    'about/': {
        'headline': 'About Us',
        'heading_1': 'Club Overview',
    },
    'about/golf-shop/': {
        'heading_1': 'Golf Shop',
    },
    'about/policies/': {
        'heading_1': 'Club Policies',
    },
    'about/team/': {
        'heading_1': 'Our Team',
    },
    'contact-us/': {
        'headline': 'Contact Us',
    },
    'daily-fee-golf/': {
        'headline': 'Daily Fee Golf',
    },
    'daily-fee-golf/book/': {
        'heading_1': 'Book a Tee Time',
    },
    'daily-fee-golf/rates/': {
        'heading_2': 'Daily Fee Rates',
    },
    'events/': {
        'headline': 'Events',
    },
    'events/golf-tournaments/': {
        'heading_1': 'Golf Tournaments',
    },
    'events/meetings/': {
        'heading_1': 'Meetings & Banquets',
    },
    'game-improvement/': {
        'headline': 'Game Improvement',
        'heading_1': "We're Here to Help",
    },
    'linkline/': {
        'headline': 'LinkLine Online',
    },
    'linkline/book-a-tee-time/': {
        'heading_1': 'Book a Tee Time',
    },
    'linkline/golf-policies/': {
        'heading_1': 'Golf Policies',
    },
    'linkline/guest-fees/': {
        'heading_2': 'Member Guest Fees',
    },
    'linkline/terms-of-use/': {
        'heading_1': 'Terms of Use',
    },
    'membership/': {
        'headline': 'Membership',
        'heading_1': 'One Membership, More Golf',
    },
    'membership/guest-fees/': {
        'heading_2': 'Member Guest Fees',
    },
    'my-account/': {
        'headline': 'My Account',
    },
    'my-account/annual-dues/': {
        'heading_1': 'Annual Dues',
    },
    'my-account/member-services/': {
        'heading_1': 'Member Services',
    },
    'my-account/payment-terms/': {
        'heading_1': 'Payment Terms',
    },
    'my-club/': {
        'headline': 'My Club',
    },
    'my-club/bistro-menus/': {
        'heading_1': 'Bistro Menus',
    },
    'news/': {
        'headline': 'My News',
    },
}


def migrate(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    ClubPage = apps.get_model('cms', 'ClubPage')
    ClubSnippet = apps.get_model('cms', 'ClubSnippet')

    for club in Club.objects.filter():
        for page_path in CREATE:
            try:
                page = ClubPage.objects.get(club=club, full_path=page_path)
            except ClubPage.DoesNotExist:
                pass
            else:
                for slug in CREATE[page_path]:
                    content = CREATE[page_path][slug]
                    snippet, _ = ClubSnippet.objects.update_or_create(
                        page=page, locale='en', slug=slug, defaults={'content': content})


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20170702_1719'),
    ]

    operations = [
        migrations.RunPython(migrate),
    ]
