# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 04:02
from __future__ import unicode_literals

from django.db import migrations


RESLUG_PAGES = [
    'golf-tournaments',
    'meetings',
    'weddings',
]


def reslug(apps, schema_editor):
    CorpPage = apps.get_model('cms', 'CorpPage')

    parent, _ = CorpPage.objects.get_or_create(
        slug='events', parent=None, defaults={'is_locked': True, 'full_path': 'events'})

    for slug in RESLUG_PAGES:
        page, _ = CorpPage.objects.get_or_create(parent=None, slug=slug)
        page.parent = parent
        page.full_path = 'events/{}'.format(slug)
        page.is_locked = True
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_auto_20170704_0317'),
    ]

    operations = [
        migrations.RunPython(reslug),
    ]
