# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 10:37
from __future__ import unicode_literals

from django.db import migrations


SYSTEM_PAGES = [
    'membership/inquiry',
]


def create_system_pages(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    ClubPage = apps.get_model('cms', 'ClubPage')

    for club in Club.objects.all():
        for path in SYSTEM_PAGES:
            base_path = path.split('/')
            slug = base_path.pop()
            base_path = '/'.join(base_path)

            parent = ClubPage.objects.get(club=club, full_path=base_path) if base_path else None
            page, _ = ClubPage.objects.get_or_create(club=club, parent=parent, slug=slug)
            page.full_path = path
            page.is_locked = True
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20170726_0546'),
    ]

    operations = [
        migrations.RunPython(create_system_pages),
    ]
