# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 08:36
from __future__ import unicode_literals

from django.db import migrations


SYSTEM_PAGES = [
    'improvement/indoor-facilties',
    'daily-fee-golf/players-club',
]


def delete_system_pages(apps, schema_editor):
    CorpPage = apps.get_model('cms', 'CorpPage')

    for path in SYSTEM_PAGES:
        CorpPage.objects.filter(full_path=path).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20170731_0004'),
    ]

    operations = [
        migrations.RunPython(delete_system_pages, lambda x, y: None),
    ]
