# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 11:25
from __future__ import unicode_literals

from django.db import migrations


SYSTEM_PAGES = [
    'shop',
]


def create_system_pages(apps, schema_editor):
    CorpPage = apps.get_model('cms', 'CorpPage')

    for path in SYSTEM_PAGES:
        base_path = path.split('/')
        slug = base_path.pop()
        base_path = '/'.join(base_path)

        parent = CorpPage.objects.get(full_path=base_path) if base_path else None
        page, _ = CorpPage.objects.get_or_create(parent=parent, slug=slug)
        page.full_path = path
        page.is_locked = True
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_auto_20170731_0436'),
    ]

    operations = [
        migrations.RunPython(create_system_pages),
    ]
