# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 05:13
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_auto_20170626_0945'),
        ('cms', '0040_auto_20170801_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('ads/club/thumbnail/'))),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('ads/club/image/'))),
                ('url', models.URLField()),
                ('sort', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='clubs.Club')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='CorpAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('ads/club/thumbnail/'))),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('ads/club/image/'))),
                ('url', models.URLField()),
                ('sort', models.IntegerField()),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
    ]
