# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 10:33
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations


COPY_IMAGES = {
    'about-bg': 'mp-news-bg',
    'membership-bg': 'mp-club-bg',
    'events-bg': 'mp-host-event-bg',
    'daily-fee-bg': 'mp-account-bg',
    'game-improvement-bg': 'mp-account-bg',
}


def copy_images(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    ClubPage = apps.get_model('cms', 'ClubPage')
    ClubImage = apps.get_model('cms', 'ClubImage')

    for club in Club.objects.all():
        page = ClubPage.objects.get(full_path='', club=club)

        for old_slug in COPY_IMAGES:
            new_slug = COPY_IMAGES[old_slug]
            try:
                image = page.images.get(slug=old_slug)
            except ClubImage.DoesNotExist:
                pass
            else:
                if default_storage.exists(image.image.name):
                    with default_storage.open(image.image.name) as f:
                        file = ContentFile(f.read())
                    file.name = image.image.name
                    ClubImage.objects.update_or_create(page=page, slug=new_slug,
                                                       defaults={'image': file})


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_auto_20170802_1321'),
    ]

    operations = [
        migrations.RunPython(copy_images,)
    ]
