# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_auto_20170804_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corppage',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
