# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_auto_20170807_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubpage',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='corppage',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='clubpage',
            name='list_in_child_page_nav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='list_in_main_menu_subnav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='name_in_child_page_nav_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='name_in_child_page_nav_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='name_in_main_menu_subnav_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='name_in_main_menu_subnav_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='show_in_main_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='show_in_page_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='list_in_child_page_nav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corppage',
            name='list_in_main_menu_subnav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corppage',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corppage',
            name='name_in_child_page_nav_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corppage',
            name='name_in_child_page_nav_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corppage',
            name='name_in_main_menu_subnav_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corppage',
            name='name_in_main_menu_subnav_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corppage',
            name='show_in_main_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='show_in_page_nav',
            field=models.BooleanField(default=True),
        ),
    ]
