# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_auto_20170807_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubpage',
            options={'ordering': ('sort',)},
        ),
        migrations.AlterModelOptions(
            name='corppage',
            options={'ordering': ('sort',)},
        ),
        migrations.RenameField(
            model_name='clubpage',
            old_name='show_in_page_nav',
            new_name='show_page_nav',
        ),
        migrations.RenameField(
            model_name='corppage',
            old_name='show_in_page_nav',
            new_name='show_page_nav',
        ),
    ]
