# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 11:31
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_auto_20170807_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='external_redirect',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='internal_redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.ClubPage'),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='should_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corppage',
            name='external_redirect',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='internal_redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.CorpPage'),
        ),
        migrations.AddField(
            model_name='corppage',
            name='should_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
