# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 11:47
from __future__ import unicode_literals

from django.db import migrations


REDIRECTS = {
    'about/our-clubs': {
        'name_en': 'Our Clubs',
        'internal_redirect': 'membership/clubs',
        'sort': 1,
        'should_redirect': True,
    },
    'events': {
        'should_redirect': True,
        'internal_redirect': 'events/weddings',
    },
    'events/special': {
        'name_en': 'Special Events',
        'should_redirect': True,
        'external_redirect': 'http://www.clublinkspecialevents.ca/',
        'sort': 2,
    },
}


def create_redirects(apps, schema_editor):
    CorpPage = apps.get_model('cms', 'CorpPage')

    for full_path in REDIRECTS:
        parent_path = full_path.split('/')
        slug = parent_path.pop()
        parent_path = '/'.join(parent_path)

        parent = None
        if parent_path:
            try:
                parent = CorpPage.objects.get(full_path=parent_path)
            except CorpPage.DoesNotExist:
                continue

        page, _ = CorpPage.objects.get_or_create(
            full_path=full_path, slug=slug, parent=parent, defaults={'is_locked': True})

        props = REDIRECTS[full_path]

        if 'internal_redirect' in props:
            try:
                props['internal_redirect'] = CorpPage.objects.get(
                    full_path=props['internal_redirect'])
            except CorpPage.DoesNotExist:
                continue

        for prop in props:
            setattr(page, prop, props[prop])

        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_auto_20170807_0731'),
    ]

    operations = [
        migrations.RunPython(create_redirects, lambda x, y: None),
    ]
