# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 17:16
from __future__ import unicode_literals

from django.db import migrations


EVERYONE_VISIBILITY = 0
MEMBERS_ONLY_VISIBILITY = 1
NON_MEMBERS_ONLY_VISIBILITY = 2


PAGE_PROPERTIES = {
    '': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Home',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': EVERYONE_VISIBILITY,
    },
    'about': {
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'About Us',
        'name_in_child_page_nav_en': 'Club Overview',
        'name_in_main_menu_subnav_en': 'Club Overview',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'about/gallery': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Gallery',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'about/golf-shop': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Shop',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 2,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'about/policies': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Club Policies',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 3,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'about/team': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Our Team',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'contact-us': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Contact Us',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 10,
        'visibility': EVERYONE_VISIBILITY,
    },
    'daily-fee-golf': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Daily Fee Golf',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 6,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'daily-fee-golf/book': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Book a Tee Time',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'daily-fee-golf/rates': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Daily Fee Rates',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'events': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Events',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 7,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/golf-tournaments': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Tournaments',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/golf-tournaments/inquiry': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/meetings': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Meetings & Banquets',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 2,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/meetings/inquiry': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/weddings': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Weddings',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': EVERYONE_VISIBILITY,
    },
    'events/weddings/inquiry': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': EVERYONE_VISIBILITY,
    },
    'game-improvement': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Game Improvement',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 8,
        'visibility': EVERYONE_VISIBILITY,
    },
    'linkline': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'LinkLine Online',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 2,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'linkline/book-a-tee-time': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Book a Tee Time',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'linkline/golf-policies': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Policies',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 2,
        'visibility': MEMBERS_ONLY_VISIBILITY
    },
    'linkline/terms-of-use': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Terms of Use',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 3,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'membership': {
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'Membership',
        'name_in_child_page_nav_en': 'Overview',
        'name_in_main_menu_subnav_en': 'Overview',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 5,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'membership/guest-fees': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Guest Fees',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'membership/inquiry': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': NON_MEMBERS_ONLY_VISIBILITY,
    },
    'my-account': {
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'My Account',
        'name_in_child_page_nav_en': 'Summary',
        'name_in_main_menu_subnav_en': 'Summary',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 4,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-account/annual-dues': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Annual Dues',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 2,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-account/member-services': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Member Services',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 4,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-account/payment-terms': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Payment Terms',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 5,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-account/statement': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Statement',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-account/update-profile': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My Profile',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-club': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My Club',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 3,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-club/bistro-menus': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Bistro Menus',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 5,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-club/calendar': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Calendar',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 0,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'my-club/roster': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Roster',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 1,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    },
    'news': {
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My News',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'show_in_main_menu': True,
        'show_in_page_nav': True,
        'sort': 9,
        'visibility': MEMBERS_ONLY_VISIBILITY,
    }
}


REDIRECTS = {
    'my-club': {
        'internal_redirect': 'my-club/calendar',
        'should_redirect': True,
    },
    'daily-fee-golf': {
        'internal_redirect': 'daily-fee-golf/book',
        'should_redirect': True,
    },
    'linkline': {
        'internal_redirect': 'linkline/book-a-tee-time',
        'should_redirect': True,
    },
    'events/special': {
        'name_en': 'Special Events',
        'should_redirect': True,
        'external_redirect': 'http://www.clublinkspecialevents.ca/',
        'sort': 3,
    },
}


def navigation_setup(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    ClubPage = apps.get_model('cms', 'ClubPage')

    for club in Club.objects.all():
        if club.slug:
            for full_path in PAGE_PROPERTIES:
                try:
                    page = ClubPage.objects.get(full_path=full_path, club=club)
                except ClubPage.DoesNotExist:
                    continue
                props = PAGE_PROPERTIES[full_path]

                for prop in props:
                    setattr(page, prop, props[prop])

                page.save()


def create_redirects(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    ClubPage = apps.get_model('cms', 'ClubPage')

    for club in Club.objects.all():
        if club.slug:
            for full_path in REDIRECTS:
                parent_path = full_path.split('/')
                slug = parent_path.pop()
                parent_path = '/'.join(parent_path)

                parent = None
                if parent_path:
                    try:
                        parent = ClubPage.objects.get(full_path=parent_path, club=club)
                    except ClubPage.DoesNotExist:
                        continue

                page, _ = ClubPage.objects.get_or_create(
                    full_path=full_path, slug=slug, parent=parent, club=club,
                    defaults={'is_locked': True})

                props = {**REDIRECTS[full_path]}

                if 'internal_redirect' in props:
                    try:
                        props['internal_redirect'] = ClubPage.objects.get(
                            full_path=props['internal_redirect'], club=club)
                    except ClubPage.DoesNotExist:
                        continue

                for prop in props:
                    setattr(page, prop, props[prop])

                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_auto_20170807_0747'),
    ]

    operations = [
        migrations.RunPython(navigation_setup, lambda x, y: None),
        migrations.RunPython(create_redirects, lambda x, y: None),
    ]
