# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 14:09
# flake8: noqa
from __future__ import unicode_literals

import clublink.cms.models
import dirtyfields.dirtyfields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_auto_20170807_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/assets/', location='/home/rehandalal/Projects/clublink/assets'), upload_to=clublink.cms.models.get_file_upload_path)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('full_path', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='cms.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cms.Folder'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('name', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('name', 'folder')]),
        ),
    ]
