# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_auto_20170809_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
