# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 06:55
# flake8: noqa
from __future__ import unicode_literals

import clublink.cms.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_auto_20170809_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/asset_files/', location='/home/rehandalal/Projects/clublink/asset_files'), upload_to=clublink.cms.models.get_file_upload_path),
        ),
    ]
