# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 21:28
# flake8: noqa
from __future__ import unicode_literals

import clublink.cms.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_auto_20170814_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/asset_files/', location='/home/rehandalal/Projects/clublink/asset_files'), upload_to=clublink.cms.models.get_file_upload_path),
        ),
    ]
