# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0069_auto_20170818_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='opens_in_new_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corppage',
            name='opens_in_new_window',
            field=models.BooleanField(default=False),
        ),
    ]
