# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 04:05
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')

    for page in ClubPage.objects.filter(full_path='linkline/book-a-tee-time'):
        page.opens_in_new_window = True
        page.save()


def reverse(apps, schema_editor):
    ClubPage = apps.get_model('cms', 'ClubPage')

    for page in ClubPage.objects.filter(full_path='linkline/book-a-tee-time'):
        page.opens_in_new_window = False
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0070_auto_20170904_0005'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
