# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0072_auto_20171103_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpadvertisement',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], default='EN', max_length=2),
        ),
    ]
