# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0074_clubadvertisement_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubgallery',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubgallery',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corpeventsgallery',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corpeventsgallery',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
