# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0075_auto_20171107_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='clubpage', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='corppage',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='corppage', to='sites.Site'),
        ),
    ]
