# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 15:52
from __future__ import unicode_literals

from django.contrib.sites.models import Site
from django.db import migrations, models
import django.db.models.deletion
from clublink.cms.models import CorpPage, ClubPage

def move_pages(apps, schema_editor):
    # For all pages already in the database, we want to assume that it is meant for the Canadian site
    site, created = Site.objects.get_or_create(domain='localhost:8000', name='Canada')
    CorpPage.objects.update(site=site)
    ClubPage.objects.update(site=site)

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0076_auto_20171111_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpage',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='corppage',
            name='sites',
        ),
        migrations.AddField(
            model_name='clubpage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubpage', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='corppage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corppage', to='sites.Site'),
        ),
        migrations.RunPython(move_pages),
    ]
