# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 02:16
from __future__ import unicode_literals

import clublink.cms.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0078_auto_20171114_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpage',
            name='hidden_bucket',
            field=models.NullBooleanField(default=False, help_text='Do not show as a bucket'),
        ),
        migrations.AlterField(
            model_name='corppage',
            name='hidden_bucket',
            field=models.NullBooleanField(default=False, help_text='Do not show as a bucket'),
        )
    ]
