# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-29 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0079_auto_20171115_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpadvertisement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corp_ads', to='sites.Site'),
        ),
    ]
