# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0080_corpadvertisement_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='use_corp_styles',
            field=models.BooleanField(default=False, help_text='This is meant to use the same background as your corp-page equivalent based on the path'),
        ),
    ]
