# Generated by Django 2.0 on 2017-12-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0081_clubpage_use_corp_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadvertisement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='clubgallery',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='clubgalleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.ClubGallery'),
        ),
        migrations.AlterField(
            model_name='clubimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.ClubPage'),
        ),
        migrations.AlterField(
            model_name='clubimageset',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='cms.ClubPage'),
        ),
        migrations.AlterField(
            model_name='clubimagesetimage',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.ClubImageSet'),
        ),
        migrations.AlterField(
            model_name='clublist',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='cms.ClubPage'),
        ),
        migrations.AlterField(
            model_name='clublistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cms.ClubList'),
        ),
        migrations.AlterField(
            model_name='clubpage',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='clubpage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubpage', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='clubpage',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Everyone'), (1, 'Members Only'), (2, 'Non-Members Only'), (3, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='clubsnippet',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='cms.ClubPage'),
        ),
        migrations.AlterField(
            model_name='corpadvertisement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corp_ads', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='corpeventsgalleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.CorpEventsGallery'),
        ),
        migrations.AlterField(
            model_name='corpimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.CorpPage'),
        ),
        migrations.AlterField(
            model_name='corpimageset',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_sets', to='cms.CorpPage'),
        ),
        migrations.AlterField(
            model_name='corpimagesetimage',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cms.CorpImageSet'),
        ),
        migrations.AlterField(
            model_name='corplist',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='cms.CorpPage'),
        ),
        migrations.AlterField(
            model_name='corplistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cms.CorpList'),
        ),
        migrations.AlterField(
            model_name='corppage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corppage', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='corpsnippet',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='cms.CorpPage'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='cms.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='cms.Folder'),
        ),
    ]
