# Generated by Django 2.0 on 2018-01-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0082_auto_20171227_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corppage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
