# Generated by Django 2.0.2 on 2018-03-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0084_auto_20180124_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='clubpage',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='corppage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='corppage',
            name='seo_title',
        ),
    ]
