# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 13:26
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership_number', models.CharField(max_length=48, null=True)),
                ('member_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_signature', models.CharField(max_length=255)),
                ('player_count', models.IntegerField()),
                ('cart_included', models.BooleanField()),
                ('expiry_date', models.DateField()),
                ('message', models.TextField(null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='clubs.Club')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.CertificateType'),
        ),
    ]
