# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 17:26
# flake8: noqa
from __future__ import unicode_literals

from hashlib import sha256

from django.db import migrations, models


def id_to_code(apps, schema_editor):
    CertificateType = apps.get_model('certificates', 'CertificateType')
    db_alias = schema_editor.connection.alias
    for c in CertificateType.objects.using(db_alias).all():
        c.certificate_code = c.id
        c.save()


def certificate_code(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    db_alias = schema_editor.connection.alias
    for c in Certificate.objects.using(db_alias).all():
        ts = '{}'.format(c.created)
        sha = sha256(ts.encode()).hexdigest()[:6]
        c.code = '{}{}{}'.format(c.type.certificate_code, c.club.certificate_code, sha)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20170206_1739'),
        ('certificates', '0002_auto_20170206_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='code',
            field=models.CharField(max_length=13, unique=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='certificate_code',
            field=models.CharField(max_length=3, unique=True, null=True),
        ),
        migrations.RunPython(id_to_code, lambda: None),
        migrations.AlterField(
            model_name='certificatetype',
            name='certificate_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.RunPython(certificate_code, lambda: None),
        migrations.AlterField(
            model_name='certificate',
            name='code',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
