# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 00:05
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20170206_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='code',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='membership_number',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
