# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 08:11
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20170212_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='member_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='membership_number',
            new_name='account_number',
        ),
    ]
