# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 08:27
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20170222_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
