# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 10:05
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20170222_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'permissions': (('can_create', 'Can create certificates'), ('can_view', 'Can view certificates'))},
        ),
    ]
