# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 15:40
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20170222_1005'),
        ('clubs', '0011_department')
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='clubs.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
