# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 06:26
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_department_club'),
        ('certificates', '0008_auto_20170222_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=clublink.base.utils.RandomizedUploadPath('certificate_ads'))),
            ],
        ),
        migrations.CreateModel(
            name='CertificateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_groups', to='clubs.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateGroupTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('cart_included', models.BooleanField()),
                ('expiry_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='certificates.CertificateGroup')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('plaintext', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='clubs.Department')),
            ],
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='player_count',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_types', to='certificates.CertificateAd'),
        ),
    ]
