# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 06:31
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20170223_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignature',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
