# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 00:14
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_emailsignature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='cart_included',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
