# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 10:49
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_auto_20170226_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
    ]
