# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 11:33
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_certificatetype_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetype',
            name='certificate_code',
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_types', to='certificates.CertificateAd'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
