# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 14:34
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_auto_20170226_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategrouptemplate',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='certificates.CertificateType'),
            preserve_default=False,
        ),
    ]
