# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_auto_20170226_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetype',
            name='guid',
        ),
    ]
