# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 19:53
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20170226_1521'),
        ('certificates', '0018_remove_certificatetype_guid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-created',), 'permissions': (('can_create', 'Can create certificates'), ('can_view', 'Can view certificates'))},
        ),
        migrations.AlterModelOptions(
            name='certificatead',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='certificategroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='emailsignature',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='certificategrouptemplate',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
