# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0020_certificatetype_dynamic_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='golf_shop',
            field=models.TextField(blank=True),
        ),
    ]
