# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 11:45
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20170226_1521'),
        ('certificates', '0021_certificatetype_golf_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.CertificateType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Department')),
            ],
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='departments',
            field=models.ManyToManyField(related_name='certificate_types', through='certificates.DepartmentCertificateType', to='clubs.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentcertificatetype',
            unique_together=set([('department', 'certificate_type')]),
        ),
    ]
