# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0022_auto_20170302_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
