# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0023_certificatetype_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
