# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0024_auto_20170302_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcertificatetype',
            name='guid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
