# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0025_departmentcertificatetype_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcertificatetype',
            name='guid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
