# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0026_auto_20170302_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='hide_recipient_name',
            field=models.BooleanField(default=False),
        ),
    ]
