# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 09:06
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0029_auto_20170306_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='players_club_clubs',
            field=models.ManyToManyField(blank=True, related_name='cpc_certificate_types', to='clubs.Club'),
        ),
    ]
