# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0031_certificatetype_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
