# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_auto_20170307_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='merchandise_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
