# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0034_auto_20170323_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='players_club_daily_fee_listing',
            field=models.BooleanField(default=False),
        ),
    ]
