# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 13:31
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0035_certificatetype_players_club_daily_fee_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.CertificateBatch'),
        ),
    ]
