# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0036_auto_20170401_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
