# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0037_certificate_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
