# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0038_auto_20170403_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
