# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 01:26
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


def populate_category(apps, schema_editor):
    CertificateType = apps.get_model('certificates', 'CertificateType')
    db_alias = schema_editor.connection.alias
    for c in CertificateType.objects.using(db_alias).all():
        if c.players_club:
            c.category = 1
        elif c.merchandise_certificate:
            c.category = 2
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0039_auto_20170403_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='category',
            field=models.IntegerField(choices=[(0, 'Default'), (1, "Player's Club"), (2, 'Merchandise')], default=0),
        ),
        migrations.RunPython(populate_category)
    ]
