# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0040_certificatetype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetype',
            name='merchandise_certificate',
        ),
        migrations.RemoveField(
            model_name='certificatetype',
            name='players_club',
        ),
    ]
