# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0041_auto_20170410_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatetype',
            old_name='golf_shop',
            new_name='redemption_details',
        ),
    ]
