# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 01:46
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0042_auto_20170410_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='redemption_location',
            field=models.CharField(choices=[('Golf Shop', 'Golf Shop'), ('Front Desk', 'Front Desk')], default='Golf Shop', max_length=64),
        ),
    ]
