# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 10:39
from __future__ import unicode_literals

from django.db import migrations


def retro_batch(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    CertificateBatch = apps.get_model('certificates', 'CertificateBatch')

    batches = []
    batch = []

    for c in Certificate.objects.order_by('id'):
        if c.batch is not None:
            batch = []
            continue

        if len(batch) == 0:
            batch.append(c)
            continue
        else:
            prev = batch[-1]

        td = c.created - prev.created

        if (c.creator == prev.creator and c.recipient_email == prev.recipient_email
                and td.days == 0 and td.seconds < 2):
            batch.append(c)
        else:
            batches.append(batch)
            batch = [c]

    batches.append(batch)

    for batch in batches:
        if len(batch):
            c = batch[0]
            b = CertificateBatch.objects.create(
                creator=c.creator, department=c.department, account_number=c.account_number,
                account_name=c.account_name, recipient_name=c.recipient_name,
                recipient_email=c.recipient_email, email_signature=c.email_signature)

            for c in batch:
                c.batch = b
                c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0044_auto_20170412_0804'),
    ]

    operations = [
        migrations.RunPython(retro_batch),
        migrations.RemoveField(
            model_name='certificate',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='email_signature',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='recipient_name',
        ),
    ]
