# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 10:58
from __future__ import unicode_literals

from django.db import migrations


def fix_batch_dates(apps, schema_editor):
    CertificateBatch = apps.get_model('certificates', 'CertificateBatch')

    for b in CertificateBatch.objects.all():
        c = b.certificates.order_by('created').first()
        b.created = c.created
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0045_auto_20170412_1039'),
    ]

    operations = [
        migrations.RunPython(fix_batch_dates),
    ]
