# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0049_certificatebatch_email_signature_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatebatch',
            name='email_signature',
        ),
        migrations.RenameField(
            model_name='certificatebatch',
            old_name='email_signature_new',
            new_name='email_signature',
        ),
    ]
