# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 04:41
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0051_auto_20170419_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='template',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'AG30 Template'), (2, 'Prestige 50 Template')], default=0),
        ),
    ]
