# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 18:49
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0054_certificatetype_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatead',
            name='image_fr',
            field=models.ImageField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('certificate_ads_fr')),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='message_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='redemption_details_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='restrictions_fr',
            field=models.TextField(blank=True),
        ),
    ]
