# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0055_auto_20170518_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignature',
            name='plaintext_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailsignature',
            name='text_fr',
            field=models.TextField(blank=True),
        ),
    ]
