# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0056_auto_20170518_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
