# Generated by Django 2.0 on 2017-12-27 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0057_certificate_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='club_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates_secondary', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.CertificateType'),
        ),
        migrations.AlterField(
            model_name='certificatebatch',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificatebatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_batches', to='clubs.Department'),
        ),
        migrations.AlterField(
            model_name='certificatebatch',
            name='email_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.EmailSignature'),
        ),
        migrations.AlterField(
            model_name='certificategroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_groups', to='clubs.Department'),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_templates', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='certificates.CertificateGroup'),
        ),
        migrations.AlterField(
            model_name='certificategrouptemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='certificates.CertificateType'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_types', to='certificates.CertificateAd'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_types', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='departmentcertificatetype',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.CertificateType'),
        ),
        migrations.AlterField(
            model_name='departmentcertificatetype',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.Department'),
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='clubs.Department'),
        ),
    ]
