# Generated by Django 2.0.2 on 2018-02-24 23:41

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0058_auto_20171227_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('certificate_headers')),
        ),
    ]
