# Generated by Django 2.0.2 on 2018-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0059_certificatetype_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='category',
            field=models.IntegerField(choices=[(0, 'Default'), (1, "Player's Club"), (2, 'Merchandise'), (3, 'Resort Stay'), (4, 'Rain Check'), (5, 'Prestige 50'), (6, 'Left Side Custom')], default=0),
        ),
    ]
