# Generated by Django 2.0.2 on 2018-03-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0061_auto_20180316_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='staging_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Staging Code'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Code'),
        ),
    ]
