# Generated by Django 2.0.2 on 2018-04-06 01:01

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0062_auto_20180316_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='double_header',
            field=models.ImageField(blank=True, help_text='2-club banner', null=True, upload_to=clublink.base.utils.RandomizedUploadPath('certificate_headers')),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='header',
            field=models.ImageField(blank=True, help_text='Single club banner', null=True, upload_to=clublink.base.utils.RandomizedUploadPath('certificate_headers')),
        ),
    ]
