# Generated by Django 2.0.2 on 2018-04-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0088_clubeventrsvp_guest_data'),
        ('certificates', '0063_auto_20180406_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategrouptemplate',
            name='club_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_certificate_templates', to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='certificategrouptemplate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificategrouptemplate',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
