# Generated by Django 2.0.2 on 2018-04-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0064_auto_20180412_2150'),
    ]

    operations = [
    ]
