# Generated by Django 2.0.2 on 2018-04-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0065_auto_20180413_1330'),
    ]

    operations = [
    ]
