CORP_SITE_PAGES = {
    # Home page
    '': {},
    'about': {},
    'about/our-clubs': {},
    'about/news': {},
    'about/employment': {},
    'daily-fee-golf': {},
    'daily-fee-golf/book': {},
    'daily-fee-golf/players-club': {},
    'golf-tournaments': {},
    'privacy-policy': {},
    'sitemap': {},
    'weddings': {},
    'meetings': {},
    'membership': {},
    'membership/promotions': {},
    'membership/clublink-life': {},
    'membership/faq': {},
    'membership/rules': {},
    'improvement': {},
    'improvement/here-to-help': {},
    'accessibility': {},
    'contact': {},
}

CLUB_SITE_PAGES = {
    '': {
        'alias': None,
        'external_redirect': '',
        'full_path': '',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Home',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': '',
        'sort': 0,
        'visibility': 0
    },
    'about': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'about',
        'internal_redirect': None,
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'About Us',
        'name_in_child_page_nav_en': 'Club Overview',
        'name_in_main_menu_subnav_en': 'Club Overview',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'about',
        'sort': 1,
        'visibility': 2
    },
    'about/gallery': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'about/gallery',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Gallery',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'gallery',
        'sort': 0,
        'visibility': 2
    },
    'about/golf-shop': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'about/golf-shop',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Shop',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'golf-shop',
        'sort': 2,
        'visibility': 2
    },
    'about/policies': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'about/policies',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Club Policies',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'policies',
        'sort': 3,
        'visibility': 2
    },
    'about/team': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'about/team',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Our Team',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'team',
        'sort': 1,
        'visibility': 2
    },
    'contact-us': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'contact-us',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Contact Us',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'contact-us',
        'sort': 10,
        'visibility': 0
    },
    'daily-fee-golf': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'daily-fee-golf',
        'internal_redirect': 'daily-fee-golf/book',
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Daily Fee Golf',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': True,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'daily-fee-golf',
        'sort': 6,
        'visibility': 2
    },
    'daily-fee-golf/book': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'daily-fee-golf/book',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Book a Tee Time',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'book',
        'sort': 0,
        'visibility': 2
    },
    'daily-fee-golf/rates': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'daily-fee-golf/rates',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Daily Fee Rates',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'rates',
        'sort': 1,
        'visibility': 2
    },
    'events': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Events',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'events',
        'sort': 7,
        'visibility': 0
    },
    'events/golf-tournaments': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/golf-tournaments',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Tournaments',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'golf-tournaments',
        'sort': 0,
        'visibility': 0
    },
    'events/golf-tournaments/inquiry': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/golf-tournaments/inquiry',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'inquiry',
        'sort': 0,
        'visibility': 0
    },
    'events/meetings': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/meetings',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Meetings & Banquets',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'meetings',
        'sort': 2,
        'visibility': 0
    },
    'events/meetings/inquiry': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/meetings/inquiry',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'inquiry',
        'sort': 0,
        'visibility': 0
    },
    'events/special': {
        'alias': None,
        'external_redirect': 'http://www.clublinkspecialevents.ca/',
        'full_path': 'events/special',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Special Events',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': True,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'special',
        'sort': 3,
        'visibility': 0
    },
    'events/weddings': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/weddings',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Weddings',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'weddings',
        'sort': 1,
        'visibility': 0
    },
    'events/weddings/inquiry': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'events/weddings/inquiry',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'inquiry',
        'sort': 0,
        'visibility': 0
    },
    'game-improvement': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'game-improvement',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Game Improvement',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'game-improvement',
        'sort': 8,
        'visibility': 0
    },
    'linkline': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'linkline',
        'internal_redirect': 'linkline/book-a-tee-time',
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'LinkLine Online',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': True,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'linkline',
        'sort': 2,
        'visibility': 1
    },
    'linkline/book-a-tee-time': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'linkline/book-a-tee-time',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Book a Tee Time',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'book-a-tee-time',
        'sort': 0,
        'visibility': 1
    },
    'linkline/golf-policies': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'linkline/golf-policies',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Policies',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'golf-policies',
        'sort': 2,
        'visibility': 1
    },
    'linkline/guest-fees': {
        'alias': 'membership/guest-fees',
        'external_redirect': '',
        'full_path': 'linkline/guest-fees',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Guest Fees',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'guest-fees',
        'sort': 1,
        'visibility': 1
    },
    'linkline/terms-of-use': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'linkline/terms-of-use',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Terms of Use',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'terms-of-use',
        'sort': 3,
        'visibility': 1
    },
    'membership': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'membership',
        'internal_redirect': None,
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'Membership',
        'name_in_child_page_nav_en': 'Overview',
        'name_in_main_menu_subnav_en': 'Overview',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'membership',
        'sort': 5,
        'visibility': 2
    },
    'membership/guest-fees': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'membership/guest-fees',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Guest Fees',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'guest-fees',
        'sort': 0,
        'visibility': 2
    },
    'membership/inquiry': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'membership/inquiry',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Request Information',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'inquiry',
        'sort': 0,
        'visibility': 2
    },
    'my-account': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account',
        'internal_redirect': None,
        'list_in_child_page_nav': True,
        'list_in_main_menu_subnav': True,
        'name_en': 'My Account',
        'name_in_child_page_nav_en': 'Summary',
        'name_in_main_menu_subnav_en': 'Summary',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'my-account',
        'sort': 4,
        'visibility': 1
    },
    'my-account/annual-dues': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account/annual-dues',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Annual Dues',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'annual-dues',
        'sort': 2,
        'visibility': 1
    },
    'my-account/member-services': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account/member-services',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Member Services',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'member-services',
        'sort': 4,
        'visibility': 1
    },
    'my-account/payment-terms': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account/payment-terms',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Payment Terms',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'payment-terms',
        'sort': 5,
        'visibility': 1
    },
    'my-account/statement': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account/statement',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Statement',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'statement',
        'sort': 0,
        'visibility': 1
    },
    'my-account/update-profile': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-account/update-profile',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My Profile',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'update-profile',
        'sort': 1,
        'visibility': 1
    },
    'my-club': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-club',
        'internal_redirect': 'my-club/calendar',
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My Club',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': True,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'my-club',
        'sort': 3,
        'visibility': 1
    },
    'my-club/bistro-menus': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-club/bistro-menus',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Bistro Menus',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'bistro-menus',
        'sort': 5,
        'visibility': 1
    },
    'my-club/calendar': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-club/calendar',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Calendar',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'calendar',
        'sort': 0,
        'visibility': 1
    },
    'my-club/gallery': {
        'alias': 'about/gallery',
        'external_redirect': '',
        'full_path': 'my-club/gallery',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Gallery',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'gallery',
        'sort': 2,
        'visibility': 1
    },
    'my-club/golf-shop': {
        'alias': 'about/golf-shop',
        'external_redirect': '',
        'full_path': 'my-club/golf-shop',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Golf Shop',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'golf-shop',
        'sort': 4,
        'visibility': 1
    },
    'my-club/our-team': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-club/our-team',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Our Team',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'our-team',
        'sort': 0,
        'visibility': 0
    },
    'my-club/roster': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'my-club/roster',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Roster',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'roster',
        'sort': 1,
        'visibility': 1
    },
    'my-club/team': {
        'alias': 'about/team',
        'external_redirect': '',
        'full_path': 'my-club/team',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'Our Team',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'team',
        'sort': 3,
        'visibility': 1
    },
    'news': {
        'alias': None,
        'external_redirect': '',
        'full_path': 'news',
        'internal_redirect': None,
        'list_in_child_page_nav': False,
        'list_in_main_menu_subnav': False,
        'name_en': 'My News',
        'name_in_child_page_nav_en': '',
        'name_in_main_menu_subnav_en': '',
        'should_redirect': False,
        'show_address_bar': True,
        'show_in_main_menu': True,
        'show_page_nav': True,
        'slug': 'news',
        'sort': 9,
        'visibility': 1
    }
}
