# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 17:39
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


def id_to_code(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    db_alias = schema_editor.connection.alias
    for c in Club.objects.using(db_alias).all():
        c.certificate_code = c.id
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='certificate_code',
            field=models.CharField(max_length=4, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(null=True, upload_to=clublink.base.utils.RandomizedUploadPath('club_logos')),
        ),
        migrations.RunPython(id_to_code, lambda: None),
        migrations.AlterField(
            model_name='club',
            name='certificate_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
