# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 00:05
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


def id_to_slug(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    db_alias = schema_editor.connection.alias
    for c in Club.objects.using(db_alias).all():
        c.slug = c.id
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20170206_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.CharField(null=True, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(id_to_slug),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
