# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 05:35
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='certificate_code',
            new_name='code',
        ),
    ]
