# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 07:44
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20170215_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='clubs.Club')),
            ],
        ),
    ]
