# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 10:48
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='academy_logo',
            field=models.ImageField(null=True, upload_to=clublink.base.utils.RandomizedUploadPath('academy_logos')),
        ),
    ]
