# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 10:49
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_academy_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fax',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
