# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:02
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_teammember_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
