# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 23:50
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='department',
            name='type',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='number',
            field=models.CharField(max_length=2),
        ),
    ]
