# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 08:52
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_department_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('sort',)},
        ),
    ]
