# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 15:21
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_auto_20170226_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clubs.Club'),
        ),
    ]
