# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models


def club_to_clubs(apps, schema_editor):
    Department = apps.get_model('clubs', 'Department')
    db_alias = schema_editor.connection.alias
    for d in Department.objects.using(db_alias).all():
        if d.club:
            d.clubs.add(d.club)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20170226_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='departments', to='clubs.Club'),
        ),
        migrations.RunPython(club_to_clubs),
        migrations.RemoveField(
            model_name='department',
            name='club',
        ),
    ]
