# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_department_tender_method_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='tender_method_guid',
        ),
    ]
