# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 02:52
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_remove_department_tender_method_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='club',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('club_logos')),
        ),
        migrations.AddField(
            model_name='club',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='clubs.Region'),
        ),
    ]
