# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_auto_20170326_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='daily_fee_location',
            field=models.BooleanField(default=False),
        ),
    ]
