# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_club_daily_fee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_resort',
            field=models.BooleanField(default=False),
        ),
    ]
