# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_club_is_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bilingual',
            field=models.BooleanField(default=False),
        ),
    ]
