# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_club_bilingual'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='latitude',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='club',
            name='longitude',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
