# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_auto_20170406_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
