# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_department_director_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='job_title',
            new_name='job_title_en',
        ),
        migrations.AddField(
            model_name='teammember',
            name='job_title_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
