# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:04
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0030_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_attendees', models.IntegerField(default=0)),
                ('attendees', models.ManyToManyField(related_name='club_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
