# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:27
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_clubevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('headline', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('club_news'))),
            ],
        ),
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ('date', 'start_time')},
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
