# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 11:02
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_auto_20170608_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubnews',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='clubs.Club'),
            preserve_default=False,
        ),
    ]
