# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 13:42
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0036_clubevent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('club_events')),
        ),
    ]
