# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 13:57
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_auto_20170608_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='type',
            field=models.IntegerField(choices=[(0, 'Member Event'), (1, 'Notice'), (2, 'Outside Event')], default=0),
            preserve_default=False,
        ),
    ]
