# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


def populate_end_date(apps, schema_editor):
    ClubEvent = apps.get_model('clubs', 'ClubEvent')

    for e in ClubEvent.objects.all():
        e.end_date = e.start_date
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_auto_20170626_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(populate_end_date),
        migrations.AlterField(
            model_name='clubevent',
            name='end_date',
            field=models.DateField(),
        )
    ]
