# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_clubevent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='description',
            field=models.TextField(),
        ),
    ]
