# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 21:21
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0041_auto_20170626_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEventRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_guests', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='attendees',
        ),
        migrations.AddField(
            model_name='clubevent',
            name='max_guests_per_rsvp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='clubs.ClubEvent'),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
