# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 08:16
from __future__ import unicode_literals

from django.db import migrations


def club_to_corp_news(apps, schema_editor):
    ClubNews = apps.get_model('clubs', 'ClubNews')
    News = apps.get_model('corp', 'News')

    for n in ClubNews.objects.all():
        news = News()
        news.publish_date = n.publish_date
        news.headline = n.headline
        news.summary = n.summary
        news.content = n.content
        news.photo = n.photo
        news.show_on_corp_site = False
        news.show_on_club_site = True
        news.save()
        news.clubs.add(n.club)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0042_auto_20170802_1721'),
        ('corp', '0004_auto_20170814_0257'),
    ]

    operations = [
        migrations.RunPython(club_to_corp_news, lambda x, y: None),
    ]
