# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0043_auto_20170814_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubnews',
            name='club',
        ),
        migrations.DeleteModel(
            name='ClubNews',
        ),
    ]
