# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-17 12:34
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import linebreaks


def linebreak_description(apps, schema_editor):
    ClubEvent = apps.get_model('clubs', 'ClubEvent')

    for e in ClubEvent.objects.all():
        e.description = linebreaks(e.description)
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0044_auto_20170814_0431'),
    ]

    operations = [
        migrations.RunPython(linebreak_description),
    ]
