# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-17 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_auto_20170817_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='svg_logo',
            field=models.FileField(blank=True, null=True, upload_to='club_logos_svg'),
        ),
    ]
