# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 12:38
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0046_club_svg_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='svg_logo',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('club_logos_svg')),
        ),
    ]
