# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0047_auto_20170818_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='resort_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='resort_weddings_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
