# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0048_auto_20170818_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('sort', 'name')},
        ),
        migrations.AddField(
            model_name='region',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
