# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0050_clubevent_online_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='custom_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
