# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-23 01:54
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0053_auto_20170822_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bistro_menu',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('bistro_menus')),
        ),
        migrations.AddField(
            model_name='club',
            name='calendar_rsvp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='event_form_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
