# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-23 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0054_auto_20170822_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubeventrsvp',
            options={'ordering': ('created',)},
        ),
    ]
