# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-13 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0056_auto_20170828_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubevent',
            old_name='custom_question',
            new_name='custom_question_1',
        ),
        migrations.RenameField(
            model_name='clubeventrsvp',
            old_name='custom_question_answer',
            new_name='custom_answer_1',
        ),
        migrations.AddField(
            model_name='clubevent',
            name='custom_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='custom_question_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='custom_question_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='custom_question_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='custom_answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='custom_answer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='custom_answer_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubeventrsvp',
            name='custom_answer_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
