# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 06:17
# flake8: noqa
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0058_auto_20170913_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banquet_menu',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('banquet_menus')),
        ),
        migrations.AddField(
            model_name='club',
            name='wedding_menu',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('wedding_menus')),
        ),
    ]
