# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0059_auto_20170921_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Field for hiding daily fees, etc.'),
        ),
    ]
