# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0060_club_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='hidden',
        ),
    ]
