# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0062_auto_20171103_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='no_weddings',
            field=models.BooleanField(default=False, help_text='Avoid default showing in weddings'),
        ),
    ]
