# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('clubs', '0063_club_no_weddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sites',
            field=models.ManyToManyField(blank=True, default=[1], null=True, to='sites.Site'),
        ),
    ]
