# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0064_club_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='sites',
            field=models.ManyToManyField(blank=True, null=True, related_name='clubs', to='sites.Site'),
        ),
    ]
