# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-06 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0067_auto_20171105_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bcg_template',
            field=models.BooleanField(default=False, help_text='This is an override for the Business Concierge Golf Club, where they have special requirements.  Realistically, this whole thing should be refactored, but that is out of scope for now.'),
        ),
    ]
