# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0069_auto_20171106_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='hide_daily_fees',
            field=models.BooleanField(default=False, help_text='If you want to hide this club from http://clublink.ca/daily-fee-golf/'),
        ),
    ]
