# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0070_auto_20171110_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='sites.Site'),
        ),
    ]
