# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('clubs', '0071_auto_20171111_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='sites',
        ),
        migrations.AddField(
            model_name='club',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='sites.Site'),
        ),
    ]
