# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.sites.models import Site
import django.db.models.deletion
from clublink.clubs.models import Club, Region

def move_regions(apps, schema_editor):
    # For all pages already in the database, we want to assume that it is meant for the Canadian site
    site, created = Site.objects.get_or_create(domain='localhost:8000', name='Canada')
    Region.objects.update(site=site)

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('clubs', '0073_auto_20171112_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='site',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.RunPython(move_regions),
    ]
