# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0075_region_tee_time_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='site',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='sites.Site'),
        ),
    ]
