# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0076_auto_20171119_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='no_meetings',
            field=models.BooleanField(default=False, help_text='Avoid default showing in meetings'),
        ),
    ]
