# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 04:33
from __future__ import unicode_literals

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0077_club_no_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='membership_brochure',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('membership_brochures')),
        ),
    ]
