# Generated by Django 2.0 on 2017-12-27 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0080_club_sales_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='clubs.Region'),
        ),
        migrations.AlterField(
            model_name='club',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='clubeventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rsvps', to='clubs.ClubEvent'),
        ),
        migrations.AlterField(
            model_name='clubeventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='site',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='clubs.Club'),
        ),
    ]
