# Generated by Django 2.0.2 on 2018-02-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0081_auto_20171227_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ('-start_date', '-start_time')},
        ),
    ]
