# Generated by Django 2.0.2 on 2018-03-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0082_auto_20180224_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ('start_date', 'start_time')},
        ),
    ]
