# Generated by Django 2.0.2 on 2018-03-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0082_auto_20180307_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='event_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clubs.EventSeries'),
        ),
    ]
