# Generated by Django 2.0.2 on 2018-03-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0083_auto_20180308_1625'),
        ('clubs', '0085_auto_20180309_1347'),
    ]

    operations = [
    ]
