# Generated by Django 2.0.2 on 2018-03-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0086_merge_20180314_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='tier',
            field=models.CharField(blank=True, choices=[('SI', 'Silver'), ('GO', 'Gold'), ('PL', 'Platinum'), ('PR', 'Prestige')], max_length=2, null=True),
        ),
    ]
