# Generated by Django 2.0.2 on 2018-03-26 15:46

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0087_club_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubeventrsvp',
            name='guest_data',
            field=django_mysql.models.JSONField(default=dict, help_text='\n        Django does not have a native in-built JSONField for MySQL.\n        Instead of hardcoding the number of guests allowable (like the below fields),\n        we are adding a JSONField to store guest data. This will also help with futureproofing \n        the model for email and contact info storage at a later point.\n        '),
        ),
    ]
