# Generated by Django 2.0.2 on 2018-04-13 02:37

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0088_clubeventrsvp_guest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banquet_menu_fr',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('banquet_menus')),
        ),
        migrations.AddField(
            model_name='club',
            name='bistro_menu_fr',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('bistro_menus')),
        ),
        migrations.AddField(
            model_name='club',
            name='membership_brochure_fr',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('membership_brochures')),
        ),
        migrations.AddField(
            model_name='club',
            name='wedding_menu_fr',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('wedding_menus')),
        ),
    ]
