# Generated by Django 2.0.2 on 2018-04-13 15:25

import clublink.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0089_auto_20180413_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='golf_tournament_menu',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('golf_tournament_menus')),
        ),
        migrations.AddField(
            model_name='club',
            name='golf_tournament_menu_fr',
            field=models.FileField(blank=True, null=True, upload_to=clublink.base.utils.RandomizedUploadPath('golf_tournament_menus')),
        ),
    ]
