# Generated by Django 2.0.2 on 2018-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0090_auto_20180413_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubeventrsvp',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
