# Generated by Django 2.0.2 on 2018-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0091_clubeventrsvp_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='email',
            field=models.EmailField(blank=True, help_text='Override for event contact', max_length=254, null=True),
        ),
    ]
